version: '3'
services:
  client:
    build:
      context: ./apps/client
    depends_on:
      - server
    ports:
      - "3333:80"

  server:
    build:
      context: ./apps/server
    depends_on:
      - mysql
      - redis
    ports:
      - "3334:3334"
    
  mysql:
    image: mysql:7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_mysql_database_name
      MYSQL_USER: root1
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
volumes:
  mysql_data:
  redis_data: